deploy 26

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -135,7 +135,7 @@ jobs:
             tar -xzf clm_next/next-build.tar.gz --overwrite
 
             echo "🚀 Restarting Next.js container with standalone build..."
-            docker restart clm_next || (echo "❌ Docker Compose failed!" && exit 1)
+            docker compose up -d --build --force-recreate --no-deps clm_next|| (echo "❌ Docker Compose failed!" && exit 1)
 
             echo "✅ Deployment complete!"
 
